### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by alexalannunes** [alexalannunes/react-spotify-api-example#1]
- [ ] add react-router-dom
- [ ] add layout and login page
- [ ] list user info
- [ ] list play list
- [ ] list playslist tracks
- [ ] show current music playing
- [ ] use useQuery or swr
